"""All user-facing strings used in the web UI.

This is the single source of truth for copy. The frontend (HTML/JS/CSS) reads
these via the /api/content endpoint, so editing copy here flows directly to the
UI without touching templates.
"""
from __future__ import annotations

CONTENT: dict[str, dict[str, str]] = {
    "connection": {
        "title": "Connect to MongoDB",
        "subtitle": "Paste a connection string. We'll detect your deployment and set things up from there.",
        "uri_label": "Connection URI",
        "uri_placeholder": "mongodb+srv://user:pass@cluster.mongodb.net/your_db",
        "db_label": "Database",
        "db_helper": "Leave blank to use the database in the URI.",
        "test_button": "Test connection",
        "footer_note": "Your connection string is stored in .env with chmod 600. It's never sent to the browser.",
        "state_connecting": "Testing connection…",
        "state_atlas": 'Connected to Atlas cluster "{name}" — native $vectorSearch available.',
        "state_replica": 'Connected to replica set "{name}" — change streams enabled, brute-force search until $vectorSearch is configured.',
        "state_standalone": "Connected to standalone MongoDB — polling mode will be used (check collection has an updated_at field for best results).",
        "error_auth": "Authentication failed. Check username, password, and that your IP is allowed in Atlas > Network Access.",
        "error_network": "Couldn't reach that host. Check the URI and try again.",
        "error_version": "MongoDB {version} is below the minimum supported version (7.0). Please upgrade or use a newer cluster.",
    },
    "collections": {
        "title": "Collections",
        "subtitle": "Pick a collection to inspect. We'll score each field for how well it fits semantic search.",
        "col_collection": "Collection",
        "col_documents": "Documents",
        "col_avg_size": "Avg size",
        "col_status": "Status",
        "row_action": "Inspect →",
        "status_not_configured": "Not configured",
        "status_configured": "Configured ({n} fields)",
        "status_indexing": "Indexing… ({n}/{total})",
        "status_ready": "Ready",
        "status_migrating": "Migrating",
        "status_failed": "Failed",
        "empty_title": "No collections yet",
        "empty_body": "This database doesn't have any collections. Add some data, then come back.",
    },
    "inspect": {
        "title": "Inspect {collection}",
        "subtitle": "We sampled {n} documents. Here's what we found.",
        "col_field": "Field path",
        "col_type": "Type",
        "col_coverage": "Coverage",
        "col_avg_length": "Avg length",
        "col_suitability": "Suitability",
        "col_action": "Action",
        "band_great": "Great",
        "band_good": "Good",
        "band_usable": "Usable",
        "band_not_recommended": "Not recommended",
        "tooltip_great": "Text field, well populated, varied content. Embed this.",
        "tooltip_good": "Usable for search. Try it.",
        "tooltip_usable": "Short or sparse. Combining with another field may help.",
        "tooltip_not_recommended": "This looks like a label or ID, not content.",
        "tooltip_array_subdoc": "Each array element gets its own embedding.",
        "action_embed": "Embed",
        "action_combine": "Combine with…",
    },
    "apply": {
        "title": "Configure semantic search",
        "subtitle": "Pick fields, a mode, and a model. You can change any of this later.",
        "section_fields": "Fields",
        "section_mode": "Mode",
        "mode_shadow": "Shadow collection (recommended)",
        "mode_shadow_helper": 'Embeddings live in "{collection}_embeddings". Your original documents are never modified.',
        "mode_inline": "Inline on source doc",
        "mode_inline_helper": 'Embeddings live in a "_msem.{field}" sub-document on each source document. No separate collection.',
        "mode_chunk_notice": "Chunking requires shadow mode. Switch to shadow or turn off chunking.",
        "section_chunking": "Chunking",
        "chunking_toggle": "Split long text into overlapping chunks",
        "chunking_help": "Chunking finds the best paragraph, not just the best document. Enable for text longer than ~1000 characters.",
        "chunking_size": "Chunk size",
        "chunking_overlap": "Overlap",
        "section_model": "Model",
        "model_local_fast": "Local Fast (MiniLM, 384d)",
        "model_local_fast_helper": "Free. Runs on your machine. Good for most use cases.",
        "model_local_better": "Local Better (MPNet, 768d)",
        "model_local_better_helper": "Free. More accurate, slower. Good for nuanced content.",
        "model_openai_small": "OpenAI Small (text-embedding-3-small, 1536d)",
        "model_openai_small_helper": "~$0.02/1M tokens. Requires OPENAI_API_KEY. Multilingual.",
        "model_openai_large": "OpenAI Large (text-embedding-3-large, 3072d)",
        "model_openai_large_helper": "~$0.13/1M tokens. Maximum accuracy.",
        "model_ollama_nomic": "Ollama (nomic-embed-text, 768d)",
        "model_ollama_nomic_helper": "Self-hosted via Ollama. Requires OLLAMA_HOST.",
        "cta_apply": "Apply configuration →",
        "notice_atlas": 'We\'ll create a $vectorSearch index named "mongosemantic_{collection}_{field}". This takes ~1 minute.',
        "notice_self_hosted": "No vector index will be created. Search uses brute-force aggregation — fine up to ~100k documents.",
    },
    "indexing": {
        "title": "Indexing {collection}",
        "subtitle": "Embedding existing documents. You can close this page — it runs in the background.",
        "metric_progress": "{processed} / {total} documents",
        "metric_rate": "{rate} docs/sec",
        "metric_eta": "ETA {duration}",
        "btn_pause": "Pause",
        "btn_cancel": "Cancel",
        "toast_started": "Indexing started.",
        "toast_paused": "Indexing paused at {n}/{total}.",
        "toast_resumed": "Indexing resumed.",
        "toast_complete": "Indexing complete — {n} documents embedded.",
        "toast_failed": "Indexing failed on {n} documents. Run retry from the dashboard.",
    },
    "search": {
        "placeholder": 'Search by meaning — "budget travel", "unhappy customers", "legal risk"',
        "toggle_hybrid": "Hybrid",
        "tooltip_hybrid": "Combines semantic similarity with keyword matching. Requires Atlas Search index.",
        "toggle_filter": "Filter…",
        "selector_all": "All configured collections",
        "result_score": "Score",
        "result_view_full": "View full document ↗",
        "empty_no_query": "Type a query above to search by meaning.",
        "empty_no_results": "No matches. Try a broader phrase, or switch to hybrid search.",
        "empty_not_configured": "No collections are configured yet. Go to Collections to set one up.",
    },
    "visualize": {
        "title": "Explore {collection}",
        "subtitle": "Documents laid out by meaning. Clusters are grouped by similarity, labeled by their top keywords.",
        "control_collection": "Collection",
        "control_clusters": "Clusters",
        "control_refresh": "Refresh",
        "empty_too_few": "Not enough embeddings to visualize. Index at least 50 documents first.",
        "tooltip_point": "Cluster: {label} · Score: {score} · Click for details",
        "coming_in": "Visualization arrives in v0.4.0.",
    },
    "aggregation": {
        "title": "Aggregation query",
        "subtitle": "Run read-only aggregation pipelines. Read-only, 10-second timeout, 100-document limit.",
        "editor_label": "Pipeline (JSON array of stages)",
        "default_pipeline": '[{ "$match": {} }, { "$limit": 20 }]',
        "safety_banner": "Blocked stages: $out, $merge, $function, any write operation. We parse before running.",
        "btn_run": "Run",
        "error_rejected": "Pipeline rejected: {reason}",
    },
    "dashboard": {
        "card_collections": "Configured collections",
        "card_total_embeddings": "Total embeddings",
        "card_coverage": "Coverage",
        "card_pending": "Pending jobs",
        "card_failed": "Failed jobs",
        "card_worker": "Worker status",
        "card_last_event": "Last change-stream event",
        "action_retry_all": "Retry all →",
        "topology_atlas": "Atlas cluster · $vectorSearch enabled",
        "topology_replica": "Replica set · change streams · brute-force search",
        "topology_standalone": "Standalone · polling (every {n}s)",
    },
    "mcp": {
        "title": "AI agent integration",
        "subtitle": "Connect Claude Desktop, Cursor, or any MCP-compatible AI agent to your MongoDB.",
        "claude_block_label": "Claude Desktop config",
        "coming_in": "MCP integration arrives in v0.3.0.",
    },
    "global": {
        "toast_saved": "Saved.",
        "toast_config_updated": "Configuration updated.",
        "toast_mongo_unreachable": "Couldn't reach MongoDB. Retrying…",
        "toast_provider_error": "Provider error: {summary}. We'll retry automatically.",
        "toast_jobs_healthy": "Job queue is healthy.",
        "toast_jobs_lagging": "Job queue is lagging by {n} items.",
        "toast_rate_limited": "Rate limited. Retrying in {n}s.",
        "onboarding_intro": "Connect a MongoDB database to begin. Once connected, we'll walk you through:",
        "onboarding_step1": "Picking a collection.",
        "onboarding_step2": "Choosing a field to make searchable.",
        "onboarding_step3": "Indexing your existing data.",
        "onboarding_summary": "Most users are set up in under a minute.",
        "nav_connection": "Connection",
        "nav_collections": "Collections",
        "nav_search": "Search",
        "nav_query": "Query",
        "nav_dashboard": "Dashboard",
        "nav_visualize": "Visualize",
        "nav_mcp": "MCP",
    },
}
